#!/usr/bin/env python3
"""Say how far the public template has fallen behind this repo.

The public mirror is generated by `.agent/skills/sync-public/sync.py`, and
nothing runs that on a schedule. So it drifts silently: on 22 Aug 2026 the
public `dashboard/` was eight days behind, `quickfind.js` was 6.2 KB against
11 KB here, and the only way to find out was to run the sync and read the diff.

This is the cheap check that makes the gap visible without writing anything. It
runs the sync into a scratch copy of the public tree and reports what would
change. No network, no writes to either repo.

The app repo has the same idea for its bundled workspace template
(`tools/export_capability_pack.py --check`, run in CI). This is the missing
twin for the public mirror.

Usage:
    python3 .agent/scripts/public_drift_check.py            # report, exit 1 on drift
    python3 .agent/scripts/public_drift_check.py --quiet    # one line, for a briefing
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SYNC = REPO_ROOT / ".agent" / "skills" / "sync-public" / "sync.py"
DEFAULT_PUBLIC = Path.home() / "repos" / "ai-second-brain"

def public_repo() -> Path:
    # Same variable the sync itself reads, so the two can never disagree
    # about which checkout is the public one.
    return Path(os.environ.get("AI_SECOND_BRAIN_REPO") or DEFAULT_PUBLIC)

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--quiet", action="store_true", help="one line only")
    args = ap.parse_args()

    public = public_repo()
    if not (public / ".git").is_dir():
        print(f"The public template is not checked out at {public}. "
              f"Set AI_SECOND_BRAIN_REPO if it lives somewhere else.", file=sys.stderr)
        return 2
    if not SYNC.is_file():
        print(f"{SYNC} is missing.", file=sys.stderr)
        return 2

    # Uncommitted work in the public tree would read as drift produced by this
    # repo, which it is not. Say so rather than guessing.
    dirty = subprocess.run(["git", "status", "--porcelain"], cwd=public,
                           capture_output=True, text=True).stdout.strip()
    if dirty:
        print(f"The public tree has {len(dirty.splitlines())} uncommitted change(s). "
              f"Commit or discard them first, or this cannot tell them from drift.")
        return 2

    with tempfile.TemporaryDirectory() as td:
        scratch = Path(td) / "public"
        # Copy the checkout, sync into the copy, and diff. The real tree is never
        # touched, so this is safe to run from a cron job or a hook.
        shutil.copytree(public, scratch, symlinks=True,
                        ignore=shutil.ignore_patterns("node_modules", "__pycache__"))
        env = {**os.environ, "AI_SECOND_BRAIN_REPO": str(scratch)}
        result = subprocess.run(
            [sys.executable, str(SYNC)],
            cwd=REPO_ROOT, capture_output=True, text=True, env=env,
        )
        if result.returncode not in (0, 2):
            print("The sync failed, so drift cannot be measured:", file=sys.stderr)
            print(result.stdout[-2000:], file=sys.stderr)
            return 2

        changed = subprocess.run(["git", "status", "--porcelain"], cwd=scratch,
                                 capture_output=True, text=True).stdout.strip()

    if not changed:
        print("Public template is current." if not args.quiet else "public template: current")
        return 0

    lines = changed.splitlines()
    added = [l for l in lines if l.startswith("??")]
    modified = [l for l in lines if l.strip().startswith("M")]
    deleted = [l for l in lines if l.strip().startswith("D")]

    if args.quiet:
        print(f"public template: {len(lines)} file(s) behind "
              f"({len(added)} new, {len(modified)} changed, {len(deleted)} removed)")
        return 1

    print(f"The public template is {len(lines)} file(s) behind this repo.")
    print(f"  {len(added)} would be added, {len(modified)} changed, {len(deleted)} removed.")
    for group, label in ((added, "new"), (modified, "changed"), (deleted, "removed")):
        for line in group[:10]:
            print(f"    {label:8} {line[3:]}")
        if len(group) > 10:
            print(f"    {label:8} ... and {len(group) - 10} more")
    print("\nRun the sync when you are ready:")
    print("  python3 .agent/skills/sync-public/sync.py           # write, audit, do not push")
    print("  python3 .agent/skills/sync-public/sync.py --push    # and push, if the audit is clean")
    return 1

if __name__ == "__main__":
    sys.exit(main())
